version: "3"
services:
  postgres_db:
    image: "postgres:11.2-alpine"
    container_name: "postgres-test"
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=garage_door
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s

  flyway:
    image: "boxfuse/flyway:5.2.4"
    container_name: "flyway-test"
    command: -url=jdbc:postgresql://postgres_db:5432/garage_door -user=postgres -password=password -connectRetries=20 migrate
    volumes:
      - ./docker/flyway/migration:/flyway/sql
    depends_on:
    - postgres_db